### ISSUE TITLE
ログイン画面修正

### ISSUE THREAD

**Issue by ogasa897** [watagassa/md2s#42]
- [ ] ログイン画面でheaderを表示しない
- [ ] ログイン画面のqiitaでログインのボタン消す
- [ ] ログイン画面がスカスカになるのでデザインどうにかする

**Comment by watagassa** [comment]
ファイル構造が変わるとコンフリクトがエグいので、この作業を行うときは、他のブランチでの作業は控えたほうがいいかも？
